name: cd

on:
  workflow_dispatch: # Allow manual runs.
  push:
    branches: [ 'main' ]

jobs:
  images:
    permissions: write-all
    name: Build images
    runs-on: ubuntu-20.04 # most compatible with debian 11

    steps:
      - uses: actions/checkout@v3
      - name: Mount bazel caches
        uses: actions/cache@v3
        with:
            path: |
                ~/.cache/bazel
                ~/.cache/bazel-repo
            key: bazel-cache-images-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', '**/*.yaml', 'WORKSPACE') }}-${{ github.sha }}
            restore-keys: |
                bazel-cache-images-
                bazel-cache-

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish images
        run: bazel --bazelrc=$GITHUB_WORKSPACE/.github/workflows/ci.bazelrc run //:publish

      - name: Publish manifests
        run: bash .cloudbuild/cloudbuild_docker.sh
