name: update-snapshots
on:
  workflow_dispatch: # Allow manual runs.
  # will send emails to last editor of this cron syntax (distroless-bot)
  schedule:
    - cron:  '35 8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go 1.20.x
      uses: actions/setup-go@v4
      id: go
      with:
        go-version: 1.20.x
        cache-dependency-path: debian_package_manager/go.sum

    - name: Run update script
      run: ./updateWorkspaceSnapshots.sh
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # v4.2.4
      with:
        author: GitHub <actions@github.com>
        committer: GitHub <actions@github.com>
        commit-message: 'feat: update packages'
        branch: feat/update-packages
        delete-branch: true
        token: ${{ steps.generate-token.outputs.token }}
        title: Update package snapshots
        body: |
          Update package snapshots
        labels: |
          dependencies
